CREATE TABLE IF NOT EXISTS `ACL_SNAPSHOT` (
  `TIMESTAMP` bigint NOT NULL,
  `OWNER_ID` bigint(20) NOT NULL,
  `OWNER_TYPE` ENUM('ENTITY', 'EVALUATION', 'TEAM') NOT NULL,
  `CREATED_ON` bigint(20) DEFAULT NULL,
  `RESOURCE_ACCESS` blob NOT NULL,
  PRIMARY KEY (`TIMESTAMP`, `OWNER_ID`, `OWNER_TYPE`),
  INDEX(CREATED_ON)
)
