CREATE TABLE IF NOT EXISTS `CERTIFIED_QUIZ_QUESTION_RECORD` (
  `RESPONSE_ID` bigint NOT NULL,
  `QUESTION_INDEX` bigint NOT NULL,
  `IS_CORRECT` bit(1) NOT NULL,
  PRIMARY KEY (`RESPONSE_ID`, `QUESTION_INDEX`),
  INDEX (QUESTION_INDEX)
)
