CREATE TABLE IF NOT EXISTS `FILE_HANDLE_RECORD` (
  `ID` bigint NOT NULL,
  `CREATED_ON` bigint NOT NULL,
  `CREATED_BY` bigint NOT NULL,
  `CONCRETE_TYPE` varchar(100) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `CONTENT_SIZE` bigint DEFAULT NULL,
  `BUCKET` varchar(100) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `_KEY` varchar(100) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `FILE_NAME` varchar(100) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `CONTENT_MD5` varchar(100) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `STORAGE_LOCATION_ID` bigint DEFAULT NULL,
  PRIMARY KEY (`ID`)
)
