CREATE TABLE IF NOT EXISTS `FILE_STATE` (
  `S3_BUCKET` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `S3_KEY` varchar(700) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `STATE` ENUM('UNKNOWN','QUEUED','COMPLETE','FAILED') NOT NULL,
  `UPDATED_ON` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ERROR_MESSAGE` varchar(3000) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `ERROR_DETAILS` mediumblob DEFAULT NULL,
  PRIMARY KEY (`S3_BUCKET`,`S3_KEY`)
)