CREATE TABLE IF NOT EXISTS `PROCESSED_ACCESS_RECORD` (
  `SESSION_ID` char(36) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `ENTITY_ID` char(7) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `CLIENT` ENUM('R','PYTHON','WEB', 'JAVA', 'COMMAND_LINE', 'ELB_HEALTHCHECKER', 'UNKNOWN') NOT NULL,
  `SYNAPSE_API` varchar(3000) CHARACTER SET latin1 COLLATE latin1_bin,
  PRIMARY KEY (`SESSION_ID`)
)
