CREATE TABLE IF NOT EXISTS `PROCESSED_ACCESS_RECORD` (
  `SESSION_ID` char(36) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `ENTITY_ID` bigint,
  `CLIENT` ENUM('R','PYTHON','WEB', 'JAVA', 'COMMAND_LINE', 'ELB_HEALTHCHECKER', 'UNKNOWN') NOT NULL,
  `NORMALIZED_METHOD_SIGNATURE` varchar(100) CHARACTER SET latin1 COLLATE latin1_bin,
  PRIMARY KEY (`SESSION_ID`)
);

CREATE INDEX PROCESSED_ACCESS_RECORD_ENTITY_ID_INDEX ON PROCESSED_ACCESS_RECORD (ENTITY_ID) USING BTREE;
CREATE INDEX PROCESSED_ACCESS_RECORD_CLIENT_INDEX ON PROCESSED_ACCESS_RECORD (CLIENT) USING BTREE;
CREATE INDEX PROCESSED_ACCESS_RECORD_NORMALIZED_METHOD_SIGNATURE_INDEX ON PROCESSED_ACCESS_RECORD (NORMALIZED_METHOD_SIGNATURE) USING BTREE
