CREATE TABLE IF NOT EXISTS `RESOURCE_ACCESS_SNAPSHOT` (
  `TIMESTAMP` bigint NOT NULL,
  `OWNER_ID` bigint(20) NOT NULL,
  `OWNER_TYPE` ENUM('ENTITY', 'EVALUATION', 'TEAM') NOT NULL,
  `PRINCIPAL_ID` bigint(20) NOT NULL,
  `ACCESS_TYPE` ENUM('CREATE', 'READ', 'UPDATE', 'DELETE', 'CHANGE_PERMISSIONS', 'DOWNLOAD', 'UPLOAD', 'PARTICIPATE', 'SUBMIT', 'READ_PRIVATE_SUBMISSION', 'UPDATE_SUBMISSION', 'DELETE_SUBMISSION', 'TEAM_MEMBERSHIP_UPDATE', 'SEND_MESSAGE', 'CHANGE_SETTINGS') NOT NULL,
  PRIMARY KEY (`TIMESTAMP`, `OWNER_ID`, `OWNER_TYPE`, `PRINCIPAL_ID`, `ACCESS_TYPE`)
)
