CREATE TABLE IF NOT EXISTS `TEAM_SNAPSHOT` (
  `TIMESTAMP` bigint NOT NULL,
  `ID` bigint(20) NOT NULL,
  `CREATED_ON` bigint(20) NOT NULL,
  `CREATED_BY` bigint(20) NOT NULL,
  `MODIFIED_ON` bigint(20) NOT NULL,
  `MODIFIED_BY` bigint(20) NOT NULL,
  `NAME` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `CAN_PUBLIC_JOIN` boolean,
  PRIMARY KEY (`ID`, `TIMESTAMP`),
  INDEX (CREATED_BY),
  INDEX (MODIFIED_BY)
)
