CREATE TABLE IF NOT EXISTS `USER_ACTIVITY_PER_CLIENT_PER_DAY` (
  `USER_ID` bigint NOT NULL,
  `X_FORWARDED_FOR` varchar(100) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `DATE` date NOT NULL,
  `CLIENT` ENUM('R','PYTHON','WEB', 'JAVA', 'COMMAND_LINE', 'ELB_HEALTHCHECKER', 'UNKNOWN', 'SYNAPSER') NOT NULL,
  PRIMARY KEY (`USER_ID`, `DATE`, `X_FORWARDED_FOR`, `CLIENT`),
  INDEX (CLIENT),
  INDEX (USER_ID),
  INDEX (DATE)
)
