CREATE TABLE IF NOT EXISTS `USER_ACTIVITY_PER_MONTH` (
  `USER_ID` bigint DEFAULT 273950,
  `X_FORWARDED_FOR` varchar(100) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `MONTH` date NOT NULL,
  `ACTIVE_DAY_COUNT` bigint NOT NULL,
  PRIMARY KEY (`USER_ID`, `X_FORWARDED_FOR`, `MONTH`),
  INDEX (MONTH),
  INDEX (USER_ID)
)
