CREATE TABLE IF NOT EXISTS `USER_ACTIVITY_PER_MONTH` (
  `USER_ID` bigint DEFAULT NULL,
  `MONTH` date NOT NULL,
  `UNIQUE_DATE` bigint NOT NULL,
  PRIMARY KEY (`USER_ID`, `MONTH`),
  INDEX (MONTH),
  INDEX (USER_ID)
)
