CREATE TABLE IF NOT EXISTS `VERIFICATION_SUBMISSION_RECORD` (
  `ID` bigint NOT NULL,
  `CREATED_ON` bigint(20) NOT NULL,
  `CREATED_BY` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX (CREATED_BY)
)
